### Send POST request with json body
POST localhost:8080/order
Content-Type: application/json

{
  "orderId": "36d2fd5c-5841-47cd-99ce-1e53b4d8801f",
  "productName": "Cola",
  "quantity": "1"
}

### Send POST request with json body
POST localhost:8080/order
Content-Type: application/json

{
  "orderId": "3161f490-c06d-4d87-abf8-85e260255ee1",
  "productName": "Ice cream",
  "quantity": "5"
}

### Send POST request with json body
POST localhost:8080/order
Content-Type: application/json

{
  "orderId": "fc620510-058d-4a5a-a480-53595ba814a5",
  "productName": "Illegal product",
  "quantity": "2"
}

### Send POST request with json body
POST localhost:8080/order
Content-Type: application/json

{
  "orderId": "f61cea87-7cf7-4973-9b54-e0de46067839",
  "productName": "Illegal product",
  "quantity": "2"
}

### Send POST request with json body
POST localhost:8080/orderFailed
Content-Type: application/json

{
  "orderId": "f61cea87-7cf7-4973-9b54-e0de46067839",
  "productName": "Bread",
  "quantity": "2"
}



### Send GET request
GET localhost:8080/order/36d2fd5c-5841-47cd-99ce-1e53b4d8801f